/*
  Copyright (c), 2023
  All rights reserved.
*/

#ifndef SYSTEMTASKS_H
#define SYSTEMTASKS_H

// Defines
/* Task Stack Size */
#define APP_DEFAULT_STACK_SIZE 3000
#define APP_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define NETWORK_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define ACC_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE

#define TAREFAS1_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define TAREFAS2_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define TAREFAS3_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define TAREFAS4_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE


/* Task Priority */
#define APP_TASK_PRIORITY 1
#define NETWORK_TASK_PRIORITY 2
#define ACC_TASK_PRIORITY 3

#define TAREFAS1_TASK_PRIORITY 6
#define TAREFAS2_TASK_PRIORITY 4 
#define TAREFAS3_TASK_PRIORITY 5
#define TAREFAS4_TASK_PRIORITY 5

/* Tasks Core */
#define APP_TASK_CORE 0
#define NETWORK_TASK_CORE 0
#define ACC_TASK_CORE 1


#define TAREFAS1_TASK_CORE 0
#define TAREFAS2_TASK_CORE 0
#define TAREFAS3_TASK_CORE 0
#define TAREFAS4_TASK_CORE 0


/* Tasks Delay */
#define APP_TASK_DELAY_MS 50
#define NETWORK_TASK_DELAY_MS 100
#define ACC_TASK_DELAY_MS 10


#define TAREFAS1_TASK_DELAY_MS 500
#define TAREFAS2_TASK_DELAY_MS 1000
#define TAREFAS3_TASK_DELAY_MS 10
#define TAREFAS4_TASK_DELAY_MS 10

#endif // #define SYSTEMTASKS_H
