#pragma once

// Defines
#define SYSTEM_TASK_LOOP false
#define SYSTEM_TASK_NOTIFY true
#define APP_DEFAULT_STACK_SIZE 3000

// Stack Size
#define BLE_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define BUTTON_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE
#define LED_TASK_STACK_SIZE APP_DEFAULT_STACK_SIZE

// Task Priority
#define BLE_TASK_PRIORITY 2
#define BUTTON_TASK_PRIORITY 1
#define LED_TASK_PRIORITY 1

// Task Core
#define BLE_TASK_CORE 0
#define BUTTON_TASK_CORE 0
#define LED_TASK_CORE 0

// Task Delay
#define BLE_TASK_DELAY_MS 1000
#define BUTTON_TASK_DELAY_MS 10
#define LED_TASK_DELAY_MS 250
#define LED_RESET_DELAY_MS 2000
#define LED_TASK_DELAY_MS_FACTOR 2

// Task mode
#define BLE_TASK_MODE SYSTEM_TASK_LOOP
#define LED_TASK_MODE SYSTEM_TASK_LOOP
#define BUTTON_TASK_MODE SYSTEM_TASK_LOOP
