/*
  Copyright (c), 2023
  All rights reserved.
*/
#pragma once

/* Defines */
#define VERBOSE_OFF 0
#define VERBOSE_ON 1

#define VERBOSE_MODULE_APP VERBOSE_OFF
#define VERBOSE_MODULE_NETWORK VERBOSE_OFF
#define VERBOSE_MODULE_ACC VERBOSE_OFF

#define VERBOSE_MODULE_STEP_APP VERBOSE_OFF
#define VERBOSE_MODULE_STEP_NETWORK VERBOSE_OFF
#define VERBOSE_MODULE_STEP_ACC VERBOSE_OFF

#define VERBOSE_TASK_APP VERBOSE_OFF
#define VERBOSE_TASK_NETWORK VERBOSE_OFF
#define VERBOSE_TASK_ACC VERBOSE_OFF
