/*
  Copyright (c), 2023
  All rights reserved.
*/
#pragma once

// Defines
#define VERBOSE_OFF 0
#define VERBOSE_ON 1

#define VERBOSE_MODULE_APP VERBOSE_OFF
#define VERBOSE_MODULE_LED VERBOSE_OFF
#define VERBOSE_MODULE_BUTTON VERBOSE_OFF

#define VERBOSE_TASK_APP VERBOSE_OFF
#define VERBOSE_TASK_LED VERBOSE_OFF
#define VERBOSE_TASK_BUTTON VERBOSE_OFF
